inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - gemfiles/*
    - spec/dummy??/**/*
    - vendor/**/*
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Lint/MissingSuper:
  Exclude:
    - 'lib/active_storage/service/db_service.rb'

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Naming/FileName:
  Exclude:
    - spec/dummy/db/*

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  # Default is 5
  Max: 15

RSpec/MultipleExpectations:
  # Default is 1
  Max: 5

RSpec/MultipleMemoizedHelpers:
  # Default is 5
  Max: 12

RSpec/NestedGroups:
  # Default is 3
  Max: 5

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/active_storage/service/db_service.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/dummy/db/**/schema*.rb

Style/NegatedIfElseCondition:
  Exclude:
    - Gemfile

Style/NumericLiterals:
  Exclude:
    - spec/dummy/db/**/schema*.rb
