inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - gemfiles/*
    - spec/dummy??/**/*
    - vendor/**/*
  TargetRubyVersion: 2.6

Lint/MissingSuper:
  Exclude:
    - 'lib/active_storage/service/db_service.rb'

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

RSpec/DescribeClass:
  Exclude:
    - spec/tasks/active_storage_db_tasks_spec.rb

RSpec/ExampleLength:
  # Default is 5
  Max: 10

RSpec/MultipleExpectations:
  # Default is 1
  Max: 5

RSpec/MultipleMemoizedHelpers:
  # Default is 5
  Max: 12

RSpec/NestedGroups:
  # Default is 3
  Max: 5

Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/active_storage/service/db_service.rb'
