inherit_from:
  - .rubocop_todo.yml
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - gemfiles/*
    - spec/dummy/**/*
    - vendor/**/*
  TargetRubyVersion: 2.6

RSpec/MultipleExpectations:
  # Default is 1
  Max: 5

RSpec/MultipleMemoizedHelpers:
  # Default is 5
  Max: 10

RSpec/NestedGroups:
  # Default is 3
  Max: 5

RSpec/ExampleLength:
  Max: 6
