services:
  app:
    container_name: 'active_storage_db_app'
    build:
      context: .
      dockerfile: ./extra/Dockerfile
      args:
        # Debian-based Ruby image:
        RUBY_IMAGE: ruby:3.4-slim
        UID: ${UID}
    environment:
      ACTIVEADMIN_VERSION: ~> 3.3
      DB_TEST: sqlite
      RAILS_VERSION: ~> 8.0
    user: "${UID}:${GID}"
    ports:
      - '3000:3000'
    working_dir: '/app'
    volumes:
      - '.:/app'
    stdin_open: true
    tty: true
    entrypoint:
      - /bin/sh
      - ./extra/entrypoint.sh
