services:
  app:
    container_name: 'active_storage_db_app'
    build:
      context: .
      dockerfile: ./extra/Dockerfile
      args:
        # Debian-based Ruby image:
        RUBY_IMAGE: ruby:${RUBY:-3.2}-slim
        RAILS_VERSION: ${RAILS:-}
        UID: ${UID}
    user: ${UID}:${GID}
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - .:/app
      - /app/spec/dummy/db
    stdin_open: true
    tty: true
    command: ${COMMAND:-sh}
