default: &default
  encoding: utf8

<% case ENV['DB_TEST']
when 'mssql' %>
test: &test
  <<: *default
  adapter: sqlserver
  host: <%= ENV.fetch('MSSQL_DB_HOST') { '127.0.0.1' } %>
  # port: <%= ENV.fetch('MSSQL_DB_PORT') { 1433 } %>
  database: <%= ENV.fetch('MSSQL_DB_NAME') { "active_storage_db_#{Rails.version.tr('.', '')}-test" } %>
  username: <%= ENV.fetch('MSSQL_DB_USERNAME') { 'sa' } %>
  password: <%= ENV.fetch('MSSQL_DB_PASSWORD') { 'Pa%%w0rd' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *test
  database: <%= "active_storage_db_#{Rails.version.tr('.', '')}-dev" %>
  schema_dump: schema-dev-mssql.rb

<% when 'mysql' %>
test: &test
  <<: *default
  adapter: mysql2
  host: <%= ENV.fetch('MYSQL_DB_HOST') { '127.0.0.1' } %>
  # port: <%= ENV.fetch('MYSQL_DB_PORT') { 3306 } %>
  database: <%= ENV.fetch('MYSQL_DB_NAME') { "active_storage_db_#{Rails.version.tr('.', '')}-test" } %>
  username: <%= ENV.fetch('MYSQL_DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_DB_PASSWORD') { 'root' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *test
  database: <%= "active_storage_db_#{Rails.version.tr('.', '')}-dev" %>
  schema_dump: schema-dev-mysql.rb

<% when 'postgres', 'postgresql' %>
test: &test
  <<: *default
  adapter: postgresql
  host: <%= ENV.fetch('PG_DB_HOST') { '127.0.0.1' } %>
  database: <%= ENV.fetch('PG_DB_NAME') { "active_storage_db_#{Rails.version.tr('.', '')}-test" } %>
  username: <%= ENV.fetch('PG_DB_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('PG_DB_PASSWORD') { 'password' } %>
  min_messages: warning
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *test
  database: <%= "active_storage_db_#{Rails.version.tr('.', '')}-dev" %>
  schema_dump: schema-dev-postgres.rb

<% else %>
test: &test
  <<: *default
  adapter: sqlite3
  database: <%= "db/active_storage_db_#{Rails.version.tr('.', '')}-test.sqlite3" %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *test
  database: <%= "db/active_storage_db_#{Rails.version.tr('.', '')}-dev.sqlite3" %>
  schema_dump: schema-dev-sqlite.rb
<% end %>
