<% case ENV['DB_TEST']
when 'mssql' %>
test: &test
  adapter: sqlserver
  host: <%= ENV.fetch('MSSQL_DB_HOST') { '127.0.0.1' } %>
  # port: <%= ENV.fetch('MSSQL_DB_PORT') { 1433 } %>
  database: <%= ENV.fetch('MSSQL_DB_NAME') { ver = Rails.version.tr('.', ''); "active_storage_db_#{ver}-test" } %>
  username: <%= ENV.fetch('MSSQL_DB_USERNAME') { '' } %>
  password: <%= ENV.fetch('MSSQL_DB_PASSWORD') { '' } %>
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *test
  database: "active_storage_db-dev"
<% when 'mysql' %>
test: &test
  adapter: mysql2
  host: <%= ENV.fetch('MYSQL_DB_HOST') { '127.0.0.1' } %>
  # port: <%= ENV.fetch('MYSQL_DB_PORT') { 3306 } %>
  database: <%= ENV.fetch('MYSQL_DB_NAME') { ver = Rails.version.tr('.', ''); "active_storage_db_#{ver}-test" } %>
  username: <%= ENV.fetch('MYSQL_DB_USERNAME') { '' } %>
  password: <%= ENV.fetch('MYSQL_DB_PASSWORD') { '' } %>
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *test
  database: "active_storage_db-dev"
<% when 'postgres', 'postgresql' %>
test: &test
  adapter: postgresql
  host: <%= ENV.fetch('PG_DB_HOST') { '127.0.0.1' } %>
  database: <%= ENV.fetch('PG_DB_NAME') { ver = Rails.version.tr('.', ''); "active_storage_db_#{ver}-test" } %>
  username: <%= ENV.fetch('PG_DB_USERNAME') { '' } %>
  password: <%= ENV.fetch('PG_DB_PASSWORD') { '' } %>
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *test
  database: "active_storage_db-dev"
<% when 'sqlite' %>
test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *test
  database: db/development.sqlite3
  schema_dump: schema_development.rb
<% else %>
  <% raise "Invalid or empty env DB_TEST #{ENV['DB_TEST']}" %>
<% end %>
