<% case ENV['DB']
when 'mysql' %>
test:
  adapter: mysql2
  host: <%= ENV.fetch('MYSQL_DB_HOST') { '127.0.0.1' } %>
  database: <%= ENV.fetch('MYSQL_DB_NAME') { 'active_storage_db_dummy_test' } %>
  username: <%= ENV.fetch('MYSQL_DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_DB_PASSWORD') { '' } %>
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
<% when 'postgres', 'postgresql' %>
test:
  adapter: postgresql
  host: <%= ENV.fetch('PG_DB_HOST') { '127.0.0.1' } %>
  database: <%= ENV.fetch('PG_DB_NAME') { 'active_storage_db_dummy_test' } %>
  username: <%= ENV.fetch('PG_DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('PG_DB_PASSWORD') { '' } %>
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
<% else %>
  <% raise "Invalid or empty env DB #{ENV['DB']}" %>
<% end %>
