FROM ruby:3.0-slim

ARG DB_TEST

RUN apt-get update
RUN apt-get install --no-install-recommends -y build-essential curl file git nano netcat libmariadb-dev libpq-dev openssl tzdata

# App setup
WORKDIR /usr/src/app
COPY .. .

# Setup the entrypoint script
COPY extra/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
