<% case ENV['DB_TEST']
when 'mysql' %>
test: &test
  adapter: mysql2
  host: <%= ENV.fetch('MYSQL_DB_HOST') { '127.0.0.1' } %>
  # port: <%= ENV.fetch('MYSQL_DB_PORT') { 3306 } %>
  database: <%= ENV.fetch('MYSQL_DB_NAME') { ver = ENV.fetch('RAILS', '').tr('.', ''); "active_storage_db_#{ver}-test" } %>
  username: <%= ENV.fetch('MYSQL_DB_USERNAME') { '' } %>
  password: <%= ENV.fetch('MYSQL_DB_PASSWORD') { '' } %>
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
<% when 'postgres', 'postgresql' %>
test: &test
  adapter: postgresql
  host: <%= ENV.fetch('PG_DB_HOST') { '127.0.0.1' } %>
  database: <%= ENV.fetch('PG_DB_NAME') { ver = ENV.fetch('RAILS', '').tr('.', ''); "active_storage_db_#{ver}-test" } %>
  username: <%= ENV.fetch('PG_DB_USERNAME') { '' } %>
  password: <%= ENV.fetch('PG_DB_PASSWORD') { '' } %>
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
<% else %>
  <% raise "Invalid or empty env DB_TEST #{ENV['DB_TEST']}" %>
<% end %>

development:
  <<: *test
  database: "active_storage_db-dev"
