---
name: Specs - MySQL

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.6', '2.7']
        gemfile: ['rails_6_1_mysql', 'rails_6_0_mysql']
        # gemfile: ['rails_7_0_mysql', 'rails_6_1_mysql', 'rails_6_0_mysql']

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      DB_TEST: mysql
      MYSQL_DB_HOST: 127.0.0.1
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root

    services:
      mysql:
        image: mysql
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        # options: >-
        #   --health-cmd="mysqladmin ping"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Start database service
        run: sudo /etc/init.d/mysql start

      - name: Create database
        run: bundle exec rails db:create

      - name: Apply migrations
        run: bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec
