---
name: Specs - Postgres

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']

    env:
      DB_TEST: postgres
      PG_DB_HOST: 127.0.0.1
      PG_DB_USERNAME: postgres
      PG_DB_PASSWORD: postgres

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Set up database
        run: bundle exec rails db:setup
      - name: Run tests
        run: bundle exec rake

#      - name: Upload coverage results
#        uses: actions/upload-artifact@master
#        if: always()
#        with:
#          name: coverage-report
#          path: coverage/index.html
