---
name: Specs Rails 7.1 Postgres

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
        gemfile: ['rails_7_1_postgres']

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      DB_TEST: postgres
      PG_DB_HOST: 127.0.0.1
      PG_DB_USERNAME: postgres
      PG_DB_PASSWORD: postgres
      RAILS: '7.0'

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install lib VIPS
        run: sudo apt-get install -y libvips-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Database setup
        run: bundle exec rails db:create db:migrate

      - name: Run tests
        run: bundle exec rspec --profile

    #  - name: Upload coverage results
    #    uses: actions/upload-artifact@main
    #    if: always()
    #    with:
    #      name: coverage-report
    #      path: coverage/index.html
