---
name: Specs Postgres Rails 7.2

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4']

    env:
      DB_TEST: postgres
      PG_DB_HOST: 127.0.0.1
      PG_DB_USERNAME: postgres
      PG_DB_PASSWORD: postgres
      RAILS_VERSION: 7.2.0

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y freetds-dev freetds-bin libvips-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Database setup
        run: bin/rails db:reset db:test:prepare

      - name: Run tests
        run: bin/rspec --profile
