---
name: Specs MySQL Rails 7.2

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.2', '3.4']

    env:
      DB_TEST: mysql
      MYSQL_DB_HOST: 127.0.0.1
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root
      RAILS_VERSION: 7.2.0

    services:
      mysql:
        image: mysql
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        # options: >-
        #   --health-cmd="mysqladmin ping"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
        ports:
          - 3306:3306

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y freetds-dev freetds-bin libvips-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Start database service
        run: sudo /etc/init.d/mysql start

      - name: Database setup
        run: bin/rails db:reset db:test:prepare

      - name: Run tests
        run: bin/rspec --profile
