---
name: Specs SQLite Rails 8.0

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4']

    env:
      DB_TEST: sqlite
      RAILS_VERSION: 8.0.0

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y freetds-dev freetds-bin libvips-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Database setup
        run: bin/rails db:reset db:test:prepare

      - name: Run tests
        run: bin/rspec --profile
