---
name: Specs Rails 7.2 MySQL

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3']
        gemfile: ['rails_7_2_mysql']

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      DB_TEST: mysql
      MYSQL_DB_HOST: 127.0.0.1
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root

    services:
      mysql:
        image: mysql
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        # options: >-
        #   --health-cmd="mysqladmin ping"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
        ports:
          - 3306:3306

    steps:
      - name: Install lib VIPS
        run: sudo apt-get install -y libvips-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Start database service
        run: sudo /etc/init.d/mysql start

      - name: Database setup
        run: bundle exec rails db:create db:migrate

      - name: Run tests
        run: bundle exec rspec --profile
