---
name: Specs MySQL Rails 8.1

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.4', '4.0']

    env:
      DB_TEST: mysql
      RAILS_VERSION: 8.1
      RUBY_VERSION: ${{ matrix.ruby }}

    steps:
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -yqq libvips-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Start database service
        run: sudo /etc/init.d/mysql start

      - name: Database setup
        run: bin/rails db:create db:migrate db:test:prepare

      - name: Run tests
        run: bin/rspec --profile
