---
name: Specs Rails 8.0 SQLite

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.2', '3.4']
        gemfile: ['rails_8_0_sqlite']

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      DB_TEST: sqlite

    steps:
      - name: Install lib VIPS
        run: sudo apt-get install -y libvips-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Database setup
        run: bundle exec rails db:create db:migrate

      - name: Run tests
        run: bundle exec rspec --profile

    #  - name: Upload coverage results
    #    uses: actions/upload-artifact@main
    #    if: always()
    #    with:
    #      name: coverage-report
    #      path: coverage/index.html
